use_frameworks!

target 'DVDZYLibTest_Example' do
  pod 'DVDZYLibTest', :path => '../'

  target 'DVDZYLibTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
